name: Test-Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5
          
      - name: Install linter
        uses: golangci/golangci-lint-action@v3
        
      - name: Lint code
        run: golangci-lint run 

      - name: Run tests
        run: go test -v ./...
        
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
      
      - name: Run gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: ./
          gofmt-flags: -l -d  
  
